build time -- 2021-04-27 15:04:16
running test_regrid_from_file
Traceback (most recent call last):
  File "src/ESMF/test/regrid_from_file/run_regrid_from_file.py", line 6, in <module>
    import ESMF.api.constants as constants
  File "/scratch1/NCEPDEV/stmp2/Mark.Potts/gfortran_9.2.0_openmpi_O_develop/src/addon/ESMPy/src/ESMF/__init__.py", line 69, in <module>
    from ESMF.api.esmpymanager import *
  File "/scratch1/NCEPDEV/stmp2/Mark.Potts/gfortran_9.2.0_openmpi_O_develop/src/addon/ESMPy/src/ESMF/api/esmpymanager.py", line 9, in <module>
    from ESMF.api.constants import *
  File "/scratch1/NCEPDEV/stmp2/Mark.Potts/gfortran_9.2.0_openmpi_O_develop/src/addon/ESMPy/src/ESMF/api/constants.py", line 3, in <module>
    import numpy as np
  File "/apps/intel/intelpython3/lib/python3.6/site-packages/numpy/__init__.py", line 156, in <module>
    from . import _distributor_init
  File "/apps/intel/intelpython3/lib/python3.6/site-packages/numpy/_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: libmkl_rt.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "setup.py", line 273, in <module>
    'test_regrid_from_file_parallel': TestRegridFromFileParallelCommand})
  File "/apps/intel/intelpython3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/apps/intel/intelpython3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/apps/intel/intelpython3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 192, in run
    subprocess.check_call(cmd)
  File "/apps/intel/intelpython3/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/apps/intel/intelpython3/bin/python3', 'src/ESMF/test/regrid_from_file/run_regrid_from_file.py']' returned non-zero exit status 1.
